import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={``}>
        <QueryProvider>
          <Toaster />
        {children}
        </QueryProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
